/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinerproject;

/**
 *
 * @author dell
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Customer = new javax.swing.JMenuItem();
        Search = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Flight = new javax.swing.JMenuItem();
        Bookflight = new javax.swing.JMenuItem();
        Ticket = new javax.swing.JMenu();
        getTicket = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Admin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Desktop.setBackground(new java.awt.Color(0, 0, 102));
        Desktop.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setForeground(new java.awt.Color(0, 0, 102));
        jMenu1.setText("Customer");
        jMenu1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Customer.setText("AddCustomer");
        Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerActionPerformed(evt);
            }
        });
        jMenu1.add(Customer);

        Search.setText("SearchCustomer");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jMenu1.add(Search);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 0, 102));
        jMenu2.setText("Flight");
        jMenu2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N

        Flight.setText("AddFlight");
        Flight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightActionPerformed(evt);
            }
        });
        jMenu2.add(Flight);

        Bookflight.setText("BookFlight");
        Bookflight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookflightActionPerformed(evt);
            }
        });
        jMenu2.add(Bookflight);

        jMenuBar1.add(jMenu2);

        Ticket.setForeground(new java.awt.Color(0, 0, 102));
        Ticket.setText("Ticket");
        Ticket.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketActionPerformed(evt);
            }
        });

        getTicket.setText("GetTicket");
        getTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTicketActionPerformed(evt);
            }
        });
        Ticket.add(getTicket);

        jMenuBar1.add(Ticket);

        jMenu4.setForeground(new java.awt.Color(0, 0, 102));
        jMenu4.setText("Admin");
        jMenu4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N

        Admin.setText("AddAdmin");
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        jMenu4.add(Admin);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerActionPerformed
       AddCustomer customer=new AddCustomer();
       Desktop.add(customer);
       customer.setVisible(true);
    }//GEN-LAST:event_CustomerActionPerformed

    private void FlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightActionPerformed
AddFlight flight=new AddFlight();
Desktop.add(flight);
       flight.setVisible(true);
    
        
    }//GEN-LAST:event_FlightActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
      AddCAdmin admin=new AddCAdmin();
Desktop.add(admin);
       admin.setVisible(true);
    }//GEN-LAST:event_AdminActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
           SearchCustomer search=new SearchCustomer();
Desktop.add(search);
       search.setVisible(true);
    }//GEN-LAST:event_SearchActionPerformed

    private void BookflightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookflightActionPerformed
       BookTicket ticket =new BookTicket();
       Desktop.add(ticket);
       ticket.setVisible(true);
    }//GEN-LAST:event_BookflightActionPerformed

    private void TicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketActionPerformed

    }//GEN-LAST:event_TicketActionPerformed

    private void getTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTicketActionPerformed
        // TODO add your handling code here:
        Getticket ticket =new  Getticket();
      Desktop.add(ticket);
      ticket.setVisible(true);
    }//GEN-LAST:event_getTicketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Admin;
    private javax.swing.JMenuItem Bookflight;
    private javax.swing.JMenuItem Customer;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem Flight;
    private javax.swing.JMenuItem Search;
    private javax.swing.JMenu Ticket;
    private javax.swing.JMenuItem getTicket;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

   
    
}
